### ISSUE TITLE
CORS and/or other error causing loading issues

### ISSUE THREAD

**Issue by watsonpaul6** [littledivy/deepdip2#1]
Using latest version of Edge on windows 11
![image](https://github.com/littledivy/deepdip2/assets/59742600/ff9594c8-4323-4c34-83fc-542e5f14ee41)
![image](https://github.com/littledivy/deepdip2/assets/59742600/cce49b0b-111e-4866-b72c-cc85aac30b95)

**Comment by littledivy** [comment]
Yeah, the records over time section is broken. Thinking of replacing it with a height-time graph per day. 

I'm currently recording live heights data every 20sec and dumping it to a GCS bucket. Shouldn't be too hard to render it

**Comment by littledivy** [comment]
Fixed with `/player?q=<name>` pages. eg: https://deepdip2.live/player?q=BrenTM
